services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    environment:
      N8N_HOST: ${N8N_HOST} # host.docker.internal
      WEBHOOK_URL: ${N8N_WEBHOOK_URL} # http://host.docker.internal:5678
      N8N_PROTOCOL: https
      N8N_PORT: 5678
      N8N_SECURE_COOKIE: true
      GENERIC_TIMEZONE:  America/Sao_Paulo
      N8N_LOG_LEVEL: debug
      N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE: true
    expose:
      - 5678
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - dev_network

  caddy:
    image: caddy:alpine
    container_name: caddy
    ports:
      - ${N8N_EXPOSE_PORT}:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/certs
    depends_on:
      - n8n
    networks:
      - dev_network

  redis:
    image: redis:latest
    container_name: n8n_redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - ${REDIS_EXPOSE_PORT}:6379
    networks:
      - dev_network

  waha:
    image: devlikeapro/waha:latest
    container_name: n8n_waha
    environment:
      WHATSAPP_HOOK_URL: ${N8N_WEBHOOK_URL}/webhook/webhook
      WHATSAPP_DEFAULT_ENGINE: GOWS
      WHATSAPP_HOOK_EVENTS: message
    ports:
      - ${WAHA_EXPOSE_PORT}:3000
    volumes:
      - waha_sessions:/home/waha/.sessions
      - waha_media:/home/waha/.media
    networks:
      - dev_network

volumes:
  n8n_data:
  pgdata:
  waha_sessions:
  waha_media:

networks:
  dev_network:
    name: ${DOCKER_NETWORK_NAME}
    external: ${DOCKER_NETWORK_EXTERNAL}
