services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    environment:
      N8N_HOST: ${N8N_HOST}
      WEBHOOK_URL: ${N8N_WEBHOOK_URL}
      N8N_PORT: 5678
      N8N_SECURE_COOKIE: false
      GENERIC_TIMEZONE: America/Sao_Paulo
      N8N_LOG_LEVEL: debug
      N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE: true
    ports:
      - ${N8N_EXPOSE_PORT}:5678
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - dev_network

  redis:
    image: redis:latest
    container_name: n8n_redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - ${REDIS_EXPOSE_PORT}:6379
    volumes:
      - n8n_redis_data:/data
    networks:
      - dev_network

  postgres:
    image: postgres:13
    container_name: n8n_postgres
    environment:
      POSTGRES_DB: waha
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - ${POSTGRES_EXPOSE_PORT}:5432
    volumes:
      - n8n_postgres_data:/var/lib/postgresql/data
    networks:
      - dev_network

  waha:
    image: devlikeapro/waha:latest
    container_name: n8n_waha
    environment:
      # Webhook - Global (não aparece no dashboard mas funciona)
      WHATSAPP_HOOK_URL: ${N8N_WEBHOOK_URL}/webhook/webhook
      WHATSAPP_HOOK_EVENTS: ${WHATSAPP_HOOK_EVENTS}
      WHATSAPP_HOOK_RETRIES_POLICY: linear
      WHATSAPP_HOOK_RETRIES_DELAY_SECONDS: 2
      WHATSAPP_HOOK_RETRIES_ATTEMPTS: 4
      
      # Engine
      WHATSAPP_DEFAULT_ENGINE: GOWS
      
      # Sessions - Storage em PostgreSQL (mais robusto)
      WHATSAPP_SESSIONS_POSTGRESQL_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/waha?sslmode=disable

      # Sessions - Auto restart
      WHATSAPP_RESTART_ALL_SESSIONS: true
      WAHA_WORKER_RESTART_SESSIONS: true
      WAHA_AUTO_START_DELAY_SECONDS: 1  # Para GOWS pode ser baixo
      WAHA_WORKER_ID: waha1
      WHATSAPP_START_SESSION: default  # Força início da sessão 'default'
      
      # Apps (se tiver WAHA Plus)
      WAHA_APPS_ENABLED: true
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379
      WAHA_API_KEY_PLAIN: ${WAHA_API_KEY}  # Para Apps precisa da versão plain
      
      # Dashboard
      WAHA_DASHBOARD_ENABLED: true
      WAHA_DASHBOARD_USERNAME: ${WAHA_DASHBOARD_USERNAME}
      WAHA_DASHBOARD_PASSWORD: ${WAHA_DASHBOARD_PASSWORD}
      
      # Swagger
      WHATSAPP_SWAGGER_ENABLED: true
      WHATSAPP_SWAGGER_USERNAME: ${WHATSAPP_SWAGGER_USERNAME}
      WHATSAPP_SWAGGER_PASSWORD: ${WHATSAPP_SWAGGER_PASSWORD}
      
      # Storage local (backup)
      WAHA_LOCAL_STORE_BASE_DIR: /app/.sessions
      
      # Timezone
      TZ: America/Sao_Paulo
      
      # Logging
      WAHA_LOG_LEVEL: info
      WAHA_LOG_FORMAT: PRETTY
      
      # Files
      WHATSAPP_FILES_FOLDER: /app/.media
      WHATSAPP_FILES_LIFETIME: 3600  # 1 hora
      
    ports:
      - ${WAHA_EXPOSE_PORT}:3000
    volumes:
      - n8n_waha_sessions:/app/.sessions
      - n8n_waha_media:/app/.media
    networks:
      - dev_network
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

volumes:
  n8n_data:
  n8n_waha_sessions:
  n8n_waha_media:
  n8n_redis_data:
  n8n_postgres_data:

networks:
  dev_network:
    name: ${DOCKER_NETWORK_NAME}
    external: ${DOCKER_NETWORK_EXTERNAL}